const recipes = [
    { 
        id: 0,
        title: "피치 크러쉬",
        drink: "피치 리큐어|스위트&사워믹스|크렌베리 주스",
        ratio: "30ml|60ml|60ml",
        memberName: "cocktail.us",
        created: "2021.08.01",
    },
    {
        id: 1,
        title: "미도리 사워", 
        drink: "미도리|스위트&사워믹스|스프라이트",
        ratio: "30ml|30ml|60ml",
        memberName: "cocktail.us",
        created: "2021.07.29",
    },
    {
        id: 2,
        title: "파우스트", 
        drink: "화이트 럼|오버프루프 럼|크렘 드 카시스",
        ratio: "30ml|30ml|15ml",
        memberName: "cocktail.us",
        created: "2021.07.28",
    },
    {
        id: 3,
        title: "블랙 러시안", 
        drink: "보드카|깔루아",
        ratio: "30ml|15ml",
        memberName: "cocktail.us",
        created: "2021.07.27",
    },
    {
        id: 4,
        title: "코스모폴리탄", 
        drink: "보드카|트리플 섹|라임 주스|크랜베리 주스",
        ratio: "30ml|15ml|15ml|15ml",
        memberName: "cocktail.us",
        created: "2021.07.25",
    },
    {
        id: 5,
        title: "스크루 드라이버", 
        drink: "보드카|오렌지주스",
        ratio: "30ml|60ml",
        memberName: "cocktail.us",
        created: "2021.07.24",
    },
    {
        id: 6,
        title: "모스코 큘", 
        drink: "보드카|라임 주스|진저 에일",
        ratio: "45ml|15ml|60ml",
        memberName: "cocktail.us",
        created: "2021.07.23",
    },
    {
        id: 7,
        title: "진 토닉", 
        drink: "진|토닉워터",
        ratio: "30ml|90ml",
        memberName: "cocktail.us",
        created: "2021.07.23",
    },
    {
        id: 8,
        title: "보드카 토닉", 
        drink: "보드카|토닉 워터",
        ratio: "60ml|120ml",
        memberName: "cocktail.us",
        created: "2021.07.23",
    },
    {
        id: 9,
        title: "하이볼", 
        drink: "위스키|레몬주스|토닉 워터",
        ratio: "45ml|30ml|60ml",
        memberName: "cocktail.us",
        created: "2021.07.23",
    },
    {
        id: 10,
        title: "모히또", 
        drink: "럼|라임주스|탄산수",
        ratio: "45ml|15ml|60ml",
        memberName: "cocktail.us",
        created: "2021.07.22",
    },
    {
        id: 11,
        title: "마가리타", 
        drink: "테킬라|트리플 섹|라임 주스",
        ratio: "30ml|15ml|15ml",
        memberName: "cocktail.us",
        created: "2021.07.22",
    },
    {
        id: 12,
        title: "김렛", 
        drink: "드라이 진|라임 주스",
        ratio: "45ml|15ml",
        memberName: "cocktail.us",
        created: "2021.07.22",
    },
    {
        id: 13,
        title: "마티니", 
        drink: "드라이 진|드라이 베르무트",
        ratio: "60ml|15ml",
        memberName: "cocktail.us",
        created: "2021.07.21",
    },
    {
        id: 14,
        title: "갓파더", 
        drink: "위스키|디사론노",
        ratio: "30ml|30ml",
        memberName: "cocktail.us",
        created: "2021.07.21",
    },
];

export default recipes;